### PR TITLE
algorithm flaw fixed

### PR DESCRIPTION
**Pull request by damiankoniecki**

### CODE REVIEW

**Comment by jarekratajski** [comment]
What a beautiful discovery. Great job. Thank YOU!

**Comment by jarekratajski** [comment]
Hi! 

Thanks for bugfix and Test!



I was wrong. Solution from damiankoniecki was OK. I had misconfigured build  on one machine.

**Comment by damiankoniecki** [comment]
Yes, that is probably a clearer solution. I wonder why there is an error after my fix though ...

**Comment by jarekratajski** [comment]
I was analysing it - your solution was ok! Sorry.
I've just found I had badly configured build on the machine.

**Pull request merged**
